Gradients:
  RoseColoredLenses:
    Name: 'Rose Colored Lenses'
    Description:
      - '<text color="#A5ACB8">The magic of this gradient lies</text>'
      - '<text color="#A5ACB8">in its ability to reveal hidden beauty</text>'
      - '<text color="#A5ACB8">and joy even in the darkest and</text>'
      - '<text color="#A5ACB8">gloomiest environments.</text>'
    Item:
      Type: 'AIR'
      Skull: ''
      ModelData: 20
    Colors:
      - '#E8CBC0'
      - '#636FA4'
  ViceCity:
    Name: 'Vice City'
    Description:
      - ''
    Colors:
      - '#3494E6'
      - '#EC6EAD'
  Radar:
    Name: 'Radar'
    Description:
      - ''
    Colors:
      - '#A770EF'
      - '#CF8BF3'
      - '#FDB99B'
  CosmicFusion:
    Name: 'Cosmic Fusion'
    Description:
      - ''
    Colors:
      - '#FF00CC'
      - '#333399'
  Nepal:
    Name: 'Nepal'
    Description:
      - ''
    Colors:
      - '#DE6161'
      - '#2657EB'
  Superman:
    Name: 'Superman'
    Description:
      - ''
    Colors:
      - '#0099F7'
      - '#F11712'
  BackToTheFuture:
    Name: 'Back to the Future'
    Description:
      - '<text color="#A5ACB8">A rare and powerful gradient</text>'
      - '<text color="#A5ACB8">coveted by time travelers</text>'
      - '<text color="#A5ACB8">and adventurers.</text>'
    Colors:
      - '#C02425'
      - '#F0CB35'
  Timber:
    Name: 'Timber'
    Description:
      - ''
    Colors:
      - '#FC00FF'
      - '#00DBDE'
  Instagram:
    Name: 'Instagram'
    Description:
      - ''
    Colors:
      - '#833AB4'
      - '#FD1D1D'
      - '#FCB045'
  MysticalAtlas:
    Name: 'Mystical Atlas'
    Description:
      - ''
    Colors:
      - '#FEAC5E'
      - '#C779D0'
      - '#4BC0C8'
  Nelson:
    Name: 'Nelson'
    Description:
      - ''
    Colors:
      - '#F2709C'
      - '#FF9472'
