name: NFTWGradients
version: 0.0.1
api-version: 1.17
author: IcyStudiosGame

main: com.nftworlds.gradients.NFTWGradientsPlugin

softdepend:
  - PlaceholderAPI

commands:
  gradient:
    aliases: [ gradients ]
